services: 
  ipregion-bot:
    image: ipregion-bot:latest
    build: 
        context: . 
        dockerfile: Dockerfile
    container_name: ipregion-bot
    restart: unless-stopped
    volumes:
      - ./databases:/app/databases
    env_file:
      - .env
    network_mode: bridge